spring:
  application:
    name: umc

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/umc_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: Admin123!

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

logging:
  level:
    com.example.umc: DEBUG
    org.hibernate.SQL: DEBUG
